services:
  frontend:
    container_name: app-frontend-blockchain
    build: ./Frontend/
    ports:
      - "3000:3000"
    environment:
      - PRODUCTION_MODE=${PRODUCTION_MODE}
      - WATCHPACK_POLLING=true 
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_URL=${API_URL}
    volumes:
      - ./Frontend/src:/srv/src/